# app/app.py
from __future__ import annotations
import json
import os
import sys

# Ensure the project root is on the path so `src` is importable
# regardless of where streamlit is invoked from.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import streamlit as st

from src.evidence import find_skill_evidence
from src.ats import ats_checks
from src.skills import extract_skills, extract_skills_dynamic, categorize_missing
from src.suggestions import generate_suggestions, generate_ai_suggestions
from src.reporting import build_report
from src.parsing import extract_text_from_pdf, read_text_input
from src.chunking import split_into_sections, bulletize, chunk_job_description
from src.embeddings import Embedder
from src.scoring import compute_section_score, weighted_overall, match_jd_to_resume

st.set_page_config(page_title="Resume–JD Analyzer", layout="wide")

st.title("Resume–Job Description Analyzer (AI)")
st.caption(
    "Upload or paste a resume and job description. "
    "Get match score, AI-powered bullet rewrites, and missing skills."
)

# ── Sidebar ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("Settings")

    model_name = st.text_input("Embedding model", value="all-MiniLM-L6-v2")

    st.markdown("#### Claude API (for AI bullet rewrites)")
    anthropic_key = st.text_input(
        "Anthropic API key (optional)",
        value=os.environ.get("ANTHROPIC_API_KEY", ""),
        type="password",
        help="If provided, bullet rewrites will be generated by Claude instead of templates.",
    )

    st.markdown("#### Section weights")
    st.caption("Drag sliders to adjust how each section contributes to the overall score.")
    w_skills = st.slider("Skills weight", 0, 100, 40)
    w_exp = st.slider("Experience weight", 0, 100, 40)
    w_proj = st.slider("Projects weight", 0, 100, 20)
    # Normalize to sum=1
    w_total = w_skills + w_exp + w_proj or 1
    custom_weights = {
        "skills": w_skills / w_total,
        "experience": w_exp / w_total,
        "projects": w_proj / w_total,
    }

    st.markdown("---")
    show_debug = st.checkbox("Show debug chunks", value=False)
    st.caption("Tip: Start with pasted text for speed. Add PDF after confirming results.")

# ── Inputs ─────────────────────────────────────────────────────────────────────
col1, col2 = st.columns(2)

with col1:
    st.subheader("Resume")
    resume_pdf = st.file_uploader("Upload Resume (PDF optional)", type=["pdf"])
    resume_text = st.text_area("Or paste resume text", height=260)

with col2:
    st.subheader("Job Description")
    jd_text = st.text_area("Paste job description", height=350)

analyze = st.button("Analyze", type="primary")

# ── Analysis ───────────────────────────────────────────────────────────────────
if analyze:
    try:
        # Parse resume
        if resume_pdf is not None:
            try:
                resume_raw = extract_text_from_pdf(resume_pdf.read())
            except Exception as e:
                st.error(f"Failed to extract text from PDF: {e}")
                st.stop()
        else:
            resume_raw = read_text_input(resume_text)

        jd_raw = read_text_input(jd_text)

        if len(resume_raw) < 200 or len(jd_raw) < 200:
            st.error(
                "Please provide more complete resume and job description text "
                "(at least ~200 characters each)."
            )
            st.stop()

        # ── Chunking ──────────────────────────────────────────────────────────
        sections = split_into_sections(resume_raw)
        jd_chunks = chunk_job_description(jd_raw)

        # Flexible section lookup: try canonical keys produced by the fuzzy splitter
        skills_text = sections.get("skills", "")
        exp_text = sections.get("experience", "")
        proj_text = sections.get("projects", "")

        skills_chunks = bulletize(skills_text) if skills_text else []
        exp_chunks = bulletize(exp_text) if exp_text else []
        proj_chunks = bulletize(proj_text) if proj_text else []

        # Fall back to full resume bullets for missing sections
        full_chunks = bulletize(sections.get("full", resume_raw))

        if not skills_chunks:
            skills_chunks = full_chunks
        if not exp_chunks:
            exp_chunks = full_chunks
        if not proj_chunks:
            proj_chunks = full_chunks

        # ── Embeddings (model is cached via lru_cache) ────────────────────────
        with st.spinner("Loading embedding model and computing scores…"):
            embedder = Embedder(model_name)
            jd_emb = embedder.embed(jd_chunks)
            skills_emb = embedder.embed(skills_chunks)
            exp_emb = embedder.embed(exp_chunks)
            proj_emb = embedder.embed(proj_chunks)

        # ── Scores ────────────────────────────────────────────────────────────
        section_scores = {
            "skills": compute_section_score(jd_emb, skills_emb),
            "experience": compute_section_score(jd_emb, exp_emb),
            "projects": compute_section_score(jd_emb, proj_emb),
        }
        overall = weighted_overall(section_scores, weights=custom_weights)
        overall_100 = round(overall * 100, 1)

        st.markdown("## Results")
        top = st.columns(4)
        top[0].metric("Overall Match", f"{overall_100}/100")
        top[1].metric("Skills Score", f"{section_scores['skills']*100:.1f}/100")
        top[2].metric("Experience Score", f"{section_scores['experience']*100:.1f}/100")
        top[3].metric("Projects Score", f"{section_scores['projects']*100:.1f}/100")

        # ── Weakest JD requirements ───────────────────────────────────────────
        resume_emb_for_match = embedder.embed(full_chunks)
        jd_to_best = match_jd_to_resume(jd_chunks, jd_emb, full_chunks, resume_emb_for_match)

        st.markdown("### Weakest-covered JD requirements (fix these first)")
        for jd_req, best_bullet, score in jd_to_best[:8]:
            label = f"Score {score*100:.1f}/100 — {jd_req[:90]}{'...' if len(jd_req) > 90 else ''}"
            with st.expander(label):
                st.write("**JD requirement:**")
                st.write(jd_req)
                st.write("**Closest resume bullet:**")
                st.write(best_bullet if best_bullet else "_No match found_")

        # ── Bullet rewrites ───────────────────────────────────────────────────
        if anthropic_key.strip():
            st.markdown("### Suggested bullet rewrites (AI-powered via Claude)")
            with st.spinner("Generating AI bullet rewrites…"):
                suggestions = generate_ai_suggestions(jd_to_best, api_key=anthropic_key.strip(), n=6)
            st.caption("Rewrites generated by Claude — fill in metric placeholders with real numbers.")
        else:
            st.markdown("### Suggested bullet rewrites (template-based)")
            suggestions = generate_suggestions(jd_to_best, n=6)
            st.caption(
                "Add an Anthropic API key in the sidebar to get AI-powered rewrites instead."
            )

        for s in suggestions:
            with st.expander(f"Score {s['score']} — Suggested rewrite"):
                st.write("**JD requirement:**")
                st.write(s["jd_req"])
                st.write("**Closest resume bullet:**")
                st.write(s["closest_bullet"] if s["closest_bullet"] else "_No match found_")
                st.write("**Suggested bullet:**")
                st.write(s["suggestion"])
                st.write("**Evidence tip:**")
                st.write(s["evidence_tip"])
                if show_debug:
                    st.caption(s.get("terms_debug", ""))

        # ── Skills ────────────────────────────────────────────────────────────
        jd_skills = extract_skills(jd_raw)
        resume_skills = extract_skills(resume_raw)

        # Also surface dynamic skills extracted from the JD
        dynamic_jd_skills = extract_skills_dynamic(jd_raw)
        dynamic_missing = dynamic_jd_skills - set(resume_raw.split())  # rough check

        missing = jd_skills - resume_skills
        grouped = categorize_missing(missing)

        st.markdown("### Skill Evidence (where skills appear in your resume)")
        present_skills = sorted(list(resume_skills))
        jd_skill_list = sorted(list(jd_skills))

        tab1, tab2, tab3 = st.tabs([
            "Skills found in Resume",
            "Skills from JD (evidence in resume)",
            "Dynamic JD skills",
        ])

        with tab1:
            st.write(present_skills if present_skills else ["None detected"])

        with tab2:
            if not jd_skill_list:
                st.info("No JD skills detected by the keyword list.")
            else:
                ev = find_skill_evidence(resume_raw, jd_skill_list, max_hits_per_skill=3)
                for sk in jd_skill_list:
                    with st.expander(sk):
                        if sk in ev:
                            for ln in ev[sk]:
                                st.write(f"- {ln}")
                        else:
                            st.write("_Not found in resume_ (add evidence if you have it)")

        with tab3:
            st.caption(
                "These are capitalized/CamelCase tokens extracted directly from the JD — "
                "tools or frameworks not in the standard skill list."
            )
            if dynamic_jd_skills:
                st.write(sorted(dynamic_jd_skills))
            else:
                st.info("No additional dynamic skills detected.")

        st.markdown("### Missing Skills (based on keyword detection)")
        c1, c2, c3 = st.columns(3)
        c1.write("**Core**")
        c1.write(grouped["core"] if grouped["core"] else ["None detected ✅"])
        c2.write("**Tools/Platforms**")
        c2.write(grouped["tools"] if grouped["tools"] else ["None detected ✅"])
        c3.write("**Nice-to-have**")
        c3.write(grouped["nice_to_have"] if grouped["nice_to_have"] else ["None detected ✅"])

        # ── ATS checks ────────────────────────────────────────────────────────
        st.markdown("### ATS checks")
        ats = ats_checks(resume_raw)

        if ats["positives"]:
            with st.expander("Positives detected", expanded=False):
                for p in ats["positives"]:
                    st.write(f"✅ {p}")

        if ats["warnings"]:
            st.warning("Potential ATS issues:")
            for w in ats["warnings"]:
                st.write(f"- {w}")
        else:
            st.success("No major ATS issues detected.")

        if ats["tips"]:
            st.info("Suggestions to improve ATS compatibility:")
            for tip in ats["tips"]:
                st.write(f"- {tip}")

        # ── Export ────────────────────────────────────────────────────────────
        st.markdown("### Export report")
        report = build_report(
            overall_100,
            section_scores,
            jd_to_best,
            grouped,
            suggestions=suggestions,
            metadata={
                "embedding_model": model_name,
                "section_weights": custom_weights,
                "ai_suggestions_used": bool(anthropic_key.strip()),
            },
        )
        report_json = json.dumps(report, indent=2)

        st.download_button(
            label="Download JSON report",
            data=report_json,
            file_name="resume_jd_report.json",
            mime="application/json",
        )

        if show_debug:
            st.code(report_json, language="json")
            st.markdown("## Debug")
            st.write("Detected sections:", list(sections.keys()))
            st.write("JD chunks (first 10):", jd_chunks[:10])
            st.write("Resume chunks (first 10):", full_chunks[:10])

    except Exception as e:
        st.error(f"An unexpected error occurred: {e}")
        if show_debug:
            import traceback
            st.code(traceback.format_exc())
